from django.urls import path
from .views import (
    login_view, 
    signup_view, 
    expense_view,
    income_view,
    habit_view,
    habit_log_view,
    task_view, mood_view,
    dashboard_view,
    history_view,
    analytics_view,
    life_score_view,
    budget_view, 
    predictor_view, 
    compare_view,
    smart_alerts_view,
    behavior_view,
    alerts_view,
    goal_view,
    daily_summary_view,
)

urlpatterns = [
    path('login/', login_view),
    path('signup/', signup_view),
    path('dashboard/<int:user_id>/', dashboard_view),
    path('expenses/<int:user_id>/', expense_view),
    path('income/<int:user_id>/', income_view),
    path('habits/<int:user_id>/', habit_view),
    path('habits/log/<int:habit_id>/', habit_log_view),
    path('tasks/<int:user_id>/', task_view),
    path('mood/<int:user_id>/', mood_view),
    path('history/<int:user_id>/', history_view),
    path('analytics/<int:user_id>/', analytics_view),
    path('lifescore/<int:user_id>/', life_score_view),
    path('budget/<int:user_id>/', budget_view),
    path('predictor/<int:user_id>/', predictor_view),
    path('compare/<int:user_id>/', compare_view),
    path('alerts/<int:user_id>/', smart_alerts_view),
    path('behavior/<int:user_id>/', behavior_view),
    path('alerts/<int:user_id>/',alerts_view),
    path('goals/<int:user_id>/', goal_view),
    path(
    'daily-summary/<int:user_id>/',daily_summary_view),
]