"""
Django settings for lifeledger_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-p!&=4d#7b^&=#eghl7*k@k69(^oppz(^o8ss32s4w$#^&33gqk'

DEBUG = True

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracker',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'x-csrftoken',
    'x-requested-with',
]

ROOT_URLCONF = 'lifeledger_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lifeledger_backend.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'Supabase@123',
        'HOST': 'db.ubcwlqajuqebuahlqddc.supabase.co',
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'

# Great question! 😊

# **Supabase IS PostgreSQL!**

# ```
# Supabase = PostgreSQL + Cloud hosting + Dashboard UI

# Think of it like:
# PostgreSQL = The database engine (the car engine)
# Supabase   = PostgreSQL + Cloud + Dashboard (the full car)
# ```

# ---

# **Simple analogy:**
# ```
# PostgreSQL = Raw database
# Supabase   = PostgreSQL with:
# #              ✅ Cloud storage
# #              ✅ Nice dashboard
# #              ✅ Auto backups
# #              ✅ Free hosting
# #              ✅ Access anywhere
# # ```

# # ---

# # **So ENGINE is always:**
# # ```python
# # 'ENGINE': 'django.db.backends.postgresql'
# # ```

# # Because Supabase uses PostgreSQL under the hood!

# # ---

# # **Just replace the PASSWORD and you're done:**
# # ```python
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'postgres',
# #         'USER': 'postgres',
# #         'PASSWORD': 'YOUR_SUPABASE_PASSWORD_HERE',  # ← only change this!
# #         'HOST': 'db.ubcwlqajuqebuahlqddc.supabase.co',
# #         'PORT': '5432',
# #     }
# # }
# # ```

# # What is your Supabase password? Enter it there and run:
# # ```powershell
# # python manage.py migrate
# # python manage.py runserver
# # ```

# # Tell me what happens! 🚀



# **Supabase cloud host!** ✅

# ```
# db.ubcwlqajuqebuahlqddc.supabase.co
# # ```

# # This is **Supabase's server in Singapore cloud** — not your laptop!

# # ---

# # **Simple picture:**

# # ```
# # Before (your laptop):
# # Django → localhost → PostgreSQL on YOUR PC
# #          ❌ Laptop off = no database

# # After (Supabase cloud):
# # Django → db.ubcwlqajuqebuahlqddc.supabase.co → Supabase Cloud
# #          ✅ Always online
# #          ✅ Laptop off = data still safe
# #          ✅ Anywhere in world
# # ```

# # ---

# # **So just paste this in `settings.py`:**

# # ```python
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'postgres',
# #         'USER': 'postgres',
# #         'PASSWORD': 'your_supabase_password',  # ← your password
# #         'HOST': 'db.ubcwlqajuqebuahlqddc.supabase.co',  # ← Supabase cloud!
# #         'PORT': '5432',
# #     }
# # }
# # ```

# # Enter your Supabase password and run:
# # ```powershell
# # python manage.py migrate
# # python manage.py runserver
# # ```

# # Data will be saved in **Supabase cloud** forever! 🚀
# Perfect understanding! 😊

# **Simple explanation:**

# ```
# Supabase IS PostgreSQL in cloud!

# When you created Supabase project:
# → Supabase automatically created PostgreSQL database
# → Named it "postgres"
# → User is "postgres"
# → You just need password!
# ```

# ---

# **You don't need to create database manually!**

# ```
# Supabase already created:
# ✅ Database name = postgres
# ✅ User = postgres
# ✅ Host = db.ubcwlqajuqebuahlqddc.supabase.co
# ✅ Port = 5432
# ❌ Password = only YOU know this
# ```

# ---

# **Think of it like this:**

# ```
# You bought a house (Supabase project)
# House comes with:
# ✅ Address (HOST)
# ✅ Room name (NAME = postgres)
# ✅ Owner name (USER = postgres)
# ❌ Your own key (PASSWORD = you set this)
# ```

# ---

# **So just enter your password:**

# ```python
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'postgres',        # Supabase default ✅
#         'USER': 'postgres',        # Supabase default ✅
#         'PASSWORD': 'xxxxxxxx',    # YOUR password ← only this!
#         'HOST': 'db.ubcwlqajuqebuahlqddc.supabase.co',  # Supabase cloud ✅
#         'PORT': '5432',            # Supabase default ✅
#     }
# }
# # ```

# # ---

# # **After this:**
# # ```powershell
# # python manage.py migrate
# # ```

# # All your tables (User, Expense, Income, Habit, Task, History, Mood) will be created automatically in Supabase cloud! 🚀

# # What is your Supabase password? 🔧
# Perfect question! Let me explain clearly! 😊

# ---

# **How it works:**

# ```
# You created tables using:
# python manage.py migrate
# → This created tables in LOCAL PostgreSQL

# Now we change settings.py to Supabase
# → Run python manage.py migrate again
# → Django creates SAME tables in Supabase cloud!
# ```

# ---

# **Simple picture:**

# ```
# Step 1 — Change settings.py
# FROM:
# 'HOST': 'localhost'  ← your laptop

# TO:
# 'HOST': 'db.ubcwlqajuqebuahlqddc.supabase.co'  ← Supabase cloud

# Step 2 — Run migrations
# python manage.py migrate
# → Django reads your models.py
# → Creates ALL tables in Supabase automatically!
# → User table ✅
# → Expense table ✅
# → Income table ✅
# → Habit table ✅
# → Task table ✅
# → History table ✅
# → Mood table ✅
# ```

# ---

# **You don't need local PostgreSQL anymore!**

# ```
# Before:
# models.py → migrate → Local PostgreSQL ❌

# After:
# models.py → migrate → Supabase Cloud ✅
# ```

# ---

# **Django doesn't care WHERE the database is!**

# ```
# Django just needs:
# ✅ Host (where is database?)
# ✅ Name (what is database name?)
# ✅ User (who am I?)
# ✅ Password (my key)

# Local PC or Cloud = doesn't matter!
# Django works same way! 🎉
# ```

# ---

# **So the process is:**

# ```
# 1. Update settings.py → Supabase details
# 2. python manage.py migrate
#    → Creates all tables in Supabase cloud
# 3. python manage.py createsuperuser
#    → Creates admin in Supabase
# 4. Run app → data saves to Supabase cloud!
# ```

# ---

# **You don't need to:**
# ```
# ❌ Create tables manually in Supabase
# ❌ Install PostgreSQL locally
# ❌ Do anything in Supabase dashboard
# ```

# **Django does everything automatically! 🚀**

# Just update `settings.py` with your Supabase password and run `migrate`! Tell me your password and let's do it! 


# Supabase automatically created database!
# # → When you created Supabase project
# # → It automatically created database called "postgres"
# # → You don't need to create manually!
# # → Just run migrate
# # → Tables created inside "postgres" database!

# # Step 1 → Update settings.py with Supabase details
# # Step 2 → python manage.py migrate
# #          → Django connects to Supabase
# #          → Creates all your tables there:
# #             ✅ tracker_user
# #             ✅ tracker_expense
# #             ✅ tracker_income
# #             ✅ tracker_habit
# #             ✅ tracker_task
# #             ✅ tracker_history
# #             ✅ tracker_mood
# # Step 3 → Run app
# #          → All data saves to Supabase! ✅


# Haha niceee 😄🔥 — that “wait how did my data suddenly appear?” moment is the best.

# Let me explain **clearly what just happened** so you fully understand (this is important for future 👇)

# ---

# # 🧠 What is “Backup” in pgAdmin?

# When you clicked **Backup**, pgAdmin created a file like:

# ```text
# lifeledger.sql
# ```

# 👉 This file is basically:

# > 📦 **A full copy of your database in SQL form**

# ---

# # 🔍 What’s inside that `.sql` file?

# It contains commands like:

# ```sql
# CREATE TABLE users (...);
# INSERT INTO users VALUES (...);
# ```

# 👉 Meaning:

# * Create tables
# * Insert all your data
# * Rebuild everything

# ---

# # 🧠 Simple analogy

# Think like this:

# * Your DB = a house 🏠
# * Backup file = blueprint + furniture list 📄

# When you run it somewhere else →
# 👉 It rebuilds the same house

# ---

# # 🚀 What you did in Supabase

# You:

# 1. Copied `.sql` file
# 2. Pasted in Supabase SQL Editor
# 3. Clicked **Run**

# ---

# ## 👉 What Supabase did:

# * Created all tables ✅
# * Inserted all data ✅
# * Rebuilt your database ✅

# ---

# # 🎉 That’s why now you see data

# Before:

# ```text
# Supabase → empty ❌
# ```

# After:

# ```text
# Supabase → full data ✅
# ```

# ---

# # 🔥 BIG WIN (important)

# Now your data is:

# * ☁️ In cloud (Supabase)
# * 🔐 Safe (even if laptop lost)
# * 🌍 Accessible anywhere

# ---

# # 🧠 Real-world concept you learned

# This is called:

# > **Database Migration**

# ---

# # 🚨 Important from now

# 👉 STOP using local pgAdmin DB
# 👉 Always use Supabase DB

# ---

# # 🚀 NEXT STEP (VERY IMPORTANT)

# Now your setup is ready for production:

# 👉 Next we must:

# ## 🔥 Deploy Django backend

# So your app works:

# * without laptop
# * for all users

# ---

# # 💬 Tell me next

# Say:

# 👉 “deploy django render step by step”

# I’ll take you to final stage 🚀💯
