# Generated by Django 6.0.2 on 2026-03-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_expense_note_expense_title_expense_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('task', 'Task Completed'), ('habit', 'Habit Completed'), ('mood', 'Mood Logged')], max_length=20)),
                ('title', models.CharField(default='', max_length=200)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2026)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracker.user')),
            ],
        ),
    ]
