# Generated by Django 6.0.2 on 2026-04-24 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_task_completed_at_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('amount', models.FloatField(default=0.0)),
                ('month', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2026)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='tracker.user')),
            ],
        ),
    ]
